version: "3.7"

services:
    zk:
        image: zookeeper:3.4.13 #zookeeper:3.6.1
        ports:
        - 2281:2181
        volumes:
        - ./data/zkdata:/data
    bk-init:
        image: apache/bookkeeper:4.10.0
        command: 
             - /bin/bash
             - -c 
             - |
             - bin/bookkeeper shell metaformat
        
    bk:
        image: apache/bookkeeper:4.10.0
        ports:
        - 3281:3281
        volumes:
        - ./data/bkdata:/data
        # - ./data/bkconf:/opt/bookkeeper/conf
        environment:
        - BK_zkServers=192.168.3.75:2281
        - BK_httpServerPort=8080
        - BK_bookiePort=3281
        - BK_advertisedAddress=192.168.3.75
        depends_on:
        - zk
        # command:  bin/bookkeeper shell metaformat -f
            # - /bin/bash
            # - -c 
            # - |
            # - bin/bookkeeper shell metaformat

    bk2:
        image: apache/bookkeeper:4.10.0
        ports:
        - 3282:3282
        volumes:
        - ./data/bkdata2:/data
        # - ./data/bkconf2:/opt/bookkeeper/conf
        environment:
        - BK_zkServers=192.168.3.75:2281
        - BK_httpServerPort=8080
        - BK_bookiePort=3282
        - BK_advertisedAddress=192.168.3.75
        depends_on:
        - zk

    bk3:
        image: apache/bookkeeper:4.10.0
        ports:
        - 3283:3283
        volumes:
        - ./data/bkdata3:/data
        # - ./data/bkconf3:/opt/bookkeeper/conf
        environment:
        - BK_zkServers=192.168.3.75:2281
        - BK_httpServerPort=8080
        - BK_bookiePort=3283
        - BK_advertisedAddress=192.168.3.75
        depends_on:
        - zk

    #TODO 需要初始化集群信息
    #TODO 部署bookkeeper集群