version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - prometheus:/etc/prometheus
      - ./data:/prometheus-data
    ports:
      - 9090:9090

volumes:
  prometheus:
